<?php
/**
 * @company MTE Telecom, Ltd.
 * @author Roman Malashin <malashinr@mte-telecom.ru>
 */
/** @var \NNX\DataGrid\GridInterface $grid */
$grid = $this->grid;

$data = $grid->getRowset();
$columns = $grid->getColumns();
$rows = [];
$escaper = $this->plugin('escapeHtml');
if (count($data) !== 0) {
    foreach ($data as $item) {
        /** @var \NNX\DataGrid\Row $item */
        $item = $item->getData();
        if (count($this->collapsedRows) && isset($item['is_leaf']) && isset($item['id']) && !$item['is_leaf']) {
            if (!in_array($item['id'], $this->collapsedRows)) {
                $item['expanded'] = true;
            }
        }
        /**
         * @var string $name
         * @var \NNX\DataGrid\Column\ColumnInterface $column
         */
        foreach ($columns as $name => $column) {
            if ($column instanceof \NNX\DataGrid\Column\ActionAwareInterface) {
                $item[$column->getName()] = '';
                $actions = $column->getActions();
                /** @var \NNX\DataGrid\Column\Action\ActionInterface $action */
                foreach ($actions as $action) {
                    $keys = array_keys($action->getAttributes());
                    $attributes = implode(' ', array_map(function ($k, $v) {
                        return $k . '="' . $v . '"';
                    }, (count($keys) !== 0 ? $keys : []), $action->getAttributes()));
                    if ($action instanceof \NNX\DataGrid\RowDataAwareInterface) {
                        $action->setRowData($item);
                    }
                    if ($action->validate()) {
                        $item[$column->getName()] .= '<a href="'
                            . $action->getUrl()
                            . '" '
                            . $attributes
                            . '>'
                            . ($action->getTitle())
                            . '</a>';
                    }
                }
            }
        }
        $rows[] = $item;
    }
}
$total = 0;
$page = 1;

if ($grid instanceof \Nnx\DataGrid\PaginatorGridInterface) {
    /** @var \Nnx\DataGrid\PaginatorGridInterface $grid */
    $paginator = $grid->getPaginator();
    $total = $paginator->count();
    $page = $paginator->getCurrentPageNumber();
}


echo json_encode((object)[
    'rows' => $rows,
    'total' => $total,
    'page' => $page
]);